# Generated by Django 3.2.2 on 2024-04-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='collegename',
            field=models.CharField(choices=[('ITM University', 'ITM University'), ('ITM College', 'ITM College')], max_length=29),
        ),
    ]
